# Generated by Django 5.2.6 on 2025-10-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('description', models.TextField(verbose_name='프로젝트 설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('figma_url', models.URLField(blank=True, verbose_name='Figma URL')),
                ('github_url', models.URLField(blank=True, verbose_name='Github URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.experience', verbose_name='회사명')),
            ],
            options={
                'verbose_name': '5.프로젝트',
                'verbose_name_plural': '5.프로젝트',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='project/file', verbose_name='프로젝트 파일')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('EXCEL', 'Excel')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.BigIntegerField(default=0, verbose_name='순서')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='프로젝트 파일')),
            ],
            options={
                'verbose_name': '프로젝트 파일',
                'verbose_name_plural': '프로젝트 파일',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project/img', verbose_name='프로젝트 이미지')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_thumnbail', models.BooleanField(default=False, verbose_name='대표 이미지')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='프로젝트명')),
            ],
            options={
                'verbose_name': '프로젝트 이미지',
                'verbose_name_plural': '프로젝트 이미지',
                'ordering': ['order'],
            },
        ),
    ]
