# Generated by Django 5.2.6 on 2025-10-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='is_thumnbail',
            new_name='is_thumnbnail',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='original_filename',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
