# Generated by Django 5.2.6 on 2025-10-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_is_thumnbail_projectimage_is_thumnbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='figma_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Figma URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='파일 타입'),
        ),
    ]
