# Generated by Django 5.2.6 on 2025-10-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_demo_url_alter_project_figma_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='is_thumnbnail',
            new_name='is_thumbnail',
        ),
    ]
