# Generated by Django 5.0.6 on 2025-10-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_is_thumnbnail_projectimage_is_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='figma_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Figma URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Github URL'),
        ),
    ]
