# Generated by Django 5.0.6 on 2025-10-16 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_drop_skill_proficiency_column'),
        ('projects', '0005_alter_project_demo_url_alter_project_figma_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, help_text='개인/기타 프로젝트는 비워두세요', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.experience', verbose_name='소속 회사/기관'),
        ),
    ]
