[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "postgresql", "nodejs"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd theme/static_src && npm install",
    "cd theme/static_src && npm run build",
    ". /opt/venv/bin/activate && python manage.py collectstatic --no-input"
]

[variables]
PATH = "/opt/venv/bin:$PATH"

[start]
cmd = "gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT --log-file -"
