# Generated by Django 5.2.6 on 2025-09-27 11:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='회사명')),
                ('position', models.CharField(max_length=100, verbose_name='직책')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('description', models.TextField(verbose_name='회사 및 업무 내용')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 재직중')),
            ],
            options={
                'verbose_name': '경력',
                'verbose_name_plural': '경력',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='메인 제목')),
                ('subtitle', models.TextField(verbose_name='부제목')),
                ('main_banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='메인 배너 이미지')),
            ],
            options={
                'verbose_name': '메인 페이지 설정',
                'verbose_name_plural': '메인 페이지 설정',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='프로필 사진')),
                ('introduce', models.TextField(verbose_name='자기 소개')),
                ('email', models.CharField(max_length=200, verbose_name='이메일')),
                ('phone', models.CharField(max_length=20, verbose_name='핸드폰')),
                ('resume_file', models.FileField(blank=True, help_text='PDF, DOC, DOCX 파일만 업로드', null=True, upload_to='resumes/', verbose_name='이력서 파일')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='스킬명')),
                ('proficiency', models.FloatField(default=0.0, verbose_name='숙련도')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('order', models.IntegerField(verbose_name='정렬순서')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='숙련도(별점)')),
            ],
            options={
                'verbose_name': '기술스택',
                'verbose_name_plural': '기술스택',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='학교명')),
                ('degree_type', models.CharField(max_length=20, verbose_name='학위')),
                ('major', models.CharField(max_length=50, verbose_name='전공')),
                ('is_major', models.BooleanField(default=True, verbose_name='주전공 여부')),
                ('start_date', models.DateField(verbose_name='입학일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='졸업일')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
