# Generated by Django 5.2.6 on 2025-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': '4.경력', 'verbose_name_plural': '4.경력'},
        ),
        migrations.AlterModelOptions(
            name='mainpagecontent',
            options={'verbose_name': '1.메인 페이지 설정', 'verbose_name_plural': '1.메인 페이지 설정'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '2.프로필', 'verbose_name_plural': '2.프로필'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': '3.기술스택', 'verbose_name_plural': '3.기술스택'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='education',
            name='minor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부전공'),
        ),
    ]
