# Generated by Django 5.2.6 on 2025-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='1988-07-26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='english_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
