# Generated by Django 5.2.6 on 2025-09-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_birth_date_profile_english_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='rating',
            new_name='level',
        ),
    ]
