# Generated by Django 5.2.6 on 2025-10-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_rating_skill_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name', 'level'], 'verbose_name': '3.기술스택', 'verbose_name_plural': '3.기술스택'},
        ),
    ]
