# Generated by Django 5.2.6 on 2025-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_skill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_intro',
            field=models.TextField(blank=True, help_text='회사에 대한 간략한 소개를 입력합니다.', verbose_name='회사 소개'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='주요 업무'),
        ),
    ]
