# Generated by Django 5.2.6 on 2025-10-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='세션 키')),
                ('question_count', models.IntegerField(default=0, verbose_name='질문 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션',
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(verbose_name='사용자 질문')),
                ('ai_response', models.TextField(verbose_name='AI 답변')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='응답시간(초)')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='사용된 토큰')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='대화시간')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai_chat.chatsession')),
            ],
            options={
                'verbose_name': '채팅 대화',
                'verbose_name_plural': '채팅 대화',
                'ordering': ['timestamp'],
            },
        ),
    ]
