"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

import os
from dotenv import load_dotenv
from django.conf import settings
import openai

load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-key-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Railway 배포 환경 지원
if 'RAILWAY_ENVIRONMENT' in os.environ:
    RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    RAILWAY_PRIVATE_DOMAIN = os.environ.get('RAILWAY_PRIVATE_DOMAIN', '')
    if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
    if RAILWAY_PRIVATE_DOMAIN and RAILWAY_PRIVATE_DOMAIN not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(RAILWAY_PRIVATE_DOMAIN)
    # Railway 도메인 와일드카드 추가
    if '.railway.app' not in str(ALLOWED_HOSTS):
        ALLOWED_HOSTS.extend(['.railway.app', '.up.railway.app'])

# CSRF 설정
CSRF_TRUSTED_ORIGINS = []
if 'RAILWAY_ENVIRONMENT' in os.environ:
    # Railway 도메인을 CSRF trusted origins에 추가
    RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
    if RAILWAY_PUBLIC_DOMAIN:
        CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')
    # Railway 도메인 패턴 추가
    CSRF_TRUSTED_ORIGINS.extend([
        'https://*.railway.app',
        'https://*.up.railway.app'
    ])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'core',
    'ai_chat',
    'projects',
]

# 개발 환경에서만 django_browser_reload 활성화
if DEBUG:
    INSTALLED_APPS.append('django_browser_reload')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 개발 환경에서만 BrowserReloadMiddleware 추가
if DEBUG:
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'portfolio' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# django-storages 및 Supabase S3 설정
# ------------------------------------------------------------------------------
# 참고: 이 설정을 위해 Railway 환경 변수에 다음이 필요합니다:
# SUPABASE_PROJECT_ID: Supabase 대시보드의 Project ID (예: rpbjeztxfmzneeoqlatn)
# SUPABASE_KEY: Supabase의 service_role 키
# SUPABASE_BUCKET: 'portfolio-media'

INSTALLED_APPS.append('storages')

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# S3Boto3Storage 설정
AWS_S3_FILE_OVERWRITE = False  # 동일한 이름의 파일이 업로드될 경우 덮어쓰지 않고, Django 기본 방식처럼 이름 뒤에 랜덤 문자열을 추가합니다.
AWS_DEFAULT_ACL = 'public-read' # 파일이 기본적으로 공개 읽기 가능하도록 설정합니다.

# Supabase S3 호환 스토리지 접속 정보
# AWS_ACCESS_KEY_ID는 Supabase의 Project ID를 사용합니다.
AWS_ACCESS_KEY_ID = config('SUPABASE_PROJECT_ID', default='')
# AWS_SECRET_ACCESS_KEY는 Supabase의 service_role 키를 사용합니다.
AWS_SECRET_ACCESS_KEY = config('SUPABASE_KEY', default='') # 기존 SUPABASE_KEY가 service_role 키여야 합니다.
AWS_STORAGE_BUCKET_NAME = config('SUPABASE_BUCKET', default='portfolio-media')
AWS_S3_ENDPOINT_URL = f"https://{config('SUPABASE_PROJECT_ID', default='')}.supabase.co/storage/v1"
AWS_S3_REGION_NAME = 'ap-northeast-2' # Supabase 프로젝트 리전 (예: ap-northeast-2)

# MEDIA_URL 설정 (django-storages가 URL을 생성하지만, 일부 경우에 대비해 설정)
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'portfolio' / 'static'
]

# WhiteNoise 설정 (프로덕션에서만 사용)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Django-Tailwind Settings
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]